'use strict';
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const {zipStore}=require('./zip');
const QRCode=require('./qrcode');
const QRErrorCorrectLevel=require('./qrcode/QRErrorCorrectLevel');

function xmlEsc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function makeDocx(title,text){const paras=[title,'',...String(text).split('\n')].map(p=>`<w:p><w:r><w:t xml:space="preserve">${xmlEsc(p)}</w:t></w:r></w:p>`).join('');const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paras}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;return zipStore([['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],['word/document.xml',doc]])}
const cp1252Extra={'€':0x80,'‚':0x82,'ƒ':0x83,'„':0x84,'…':0x85,'†':0x86,'‡':0x87,'ˆ':0x88,'‰':0x89,'Š':0x8a,'‹':0x8b,'Œ':0x8c,'Ž':0x8e,'‘':0x91,'’':0x92,'“':0x93,'”':0x94,'•':0x95,'–':0x96,'—':0x97,'˜':0x98,'™':0x99,'š':0x9a,'›':0x9b,'œ':0x9c,'ž':0x9e,'Ÿ':0x9f};
function cp1252(s){const a=[];for(const ch of String(s)){const n=ch.codePointAt(0);if(n<=255)a.push(n);else if(cp1252Extra[ch]!=null)a.push(cp1252Extra[ch]);else a.push(63)}return Buffer.from(a)}
function pdfEscBuffer(s){const b=cp1252(s),out=[];for(const x of b){if(x===40||x===41||x===92)out.push(92,x);else out.push(x)}return Buffer.from(out)}
function wrapText(text,width=86){const lines=[];for(const para of String(text).split('\n')){if(!para.trim()){lines.push('');continue}let cur='';for(const w of para.split(/\s+/)){if((cur+' '+w).trim().length>width){if(cur)lines.push(cur);cur=w}else cur=(cur?cur+' ':'')+w}if(cur)lines.push(cur)}return lines}
function makePdf(title,text){const lines=[title,'',...wrapText(text)],pages=[];for(let i=0;i<lines.length;i+=46)pages.push(lines.slice(i,i+46));if(!pages.length)pages.push(['']);const objs=[];const add=b=>{objs.push(Buffer.isBuffer(b)?b:Buffer.from(b,'binary'));return objs.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');const pageIds=[],contentIds=[];for(const pg of pages){let chunks=[Buffer.from('BT\n/F1 11 Tf\n50 790 Td\n14 TL\n','binary')];pg.forEach((ln,idx)=>{if(idx)chunks.push(Buffer.from('T*\n','binary'));chunks.push(Buffer.from('(','binary'),pdfEscBuffer(ln),Buffer.from(') Tj\n','binary'))});chunks.push(Buffer.from('ET','binary'));const stream=Buffer.concat(chunks),cid=add(Buffer.concat([Buffer.from(`<< /Length ${stream.length} >>\nstream\n`,'binary'),stream,Buffer.from('\nendstream','binary')]));contentIds.push(cid);pageIds.push(add('PENDING'))}const pagesId=add('PENDING');for(let i=0;i<pageIds.length;i++)objs[pageIds[i]-1]=Buffer.from(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`,'binary');objs[pagesId-1]=Buffer.from(`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`,'binary');const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let out=[Buffer.from('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n','binary')],offsets=[0],pos=out[0].length;for(let i=0;i<objs.length;i++){offsets.push(pos);const p=Buffer.concat([Buffer.from(`${i+1} 0 obj\n`,'binary'),objs[i],Buffer.from('\nendobj\n','binary')]);out.push(p);pos+=p.length}const xref=pos;let xs=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)xs+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';xs+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;out.push(Buffer.from(xs,'binary'));return Buffer.concat(out)}
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function pngChunk(type,data){const tb=Buffer.from(type);const len=Buffer.alloc(4);len.writeUInt32BE(data.length);const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(Buffer.concat([tb,data])));return Buffer.concat([len,tb,data,crc])}
function makePng(width,height,pixel){const rows=[];for(let y=0;y<height;y++){const row=Buffer.alloc(1+width*4);row[0]=0;for(let x=0;x<width;x++){const [r,g,b,a=255]=pixel(x,y);const i=1+x*4;row[i]=r;row[i+1]=g;row[i+2]=b;row[i+3]=a}rows.push(row)}const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(width,0);ihdr.writeUInt32BE(height,4);ihdr[8]=8;ihdr[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),pngChunk('IHDR',ihdr),pngChunk('IDAT',zlib.deflateSync(Buffer.concat(rows),{level:9})),pngChunk('IEND',Buffer.alloc(0))])}
function qrMatrix(text){const qr=new QRCode(0,QRErrorCorrectLevel.M);qr.addData(String(text));qr.make();const n=qr.getModuleCount(),m=[];for(let r=0;r<n;r++){m[r]=[];for(let c=0;c<n;c++)m[r][c]=qr.isDark(r,c)}return m}
function makeQrPng(text,size=720){const m=qrMatrix(text),quiet=4,n=m.length+quiet*2,scale=Math.max(1,Math.floor(size/n)),real=n*scale;return makePng(real,real,(x,y)=>{const cx=Math.floor(x/scale)-quiet,cy=Math.floor(y/scale)-quiet;const dark=cx>=0&&cy>=0&&cx<m.length&&cy<m.length&&m[cy][cx];return dark?[0,0,0,255]:[255,255,255,255]})}
function makeQrSvg(text){const m=qrMatrix(text),q=4,n=m.length+q*2;let d='';for(let r=0;r<m.length;r++)for(let c=0;c<m.length;c++)if(m[r][c])d+=`M${c+q},${r+q}h1v1h-1z`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n} ${n}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path d="${d}" fill="black"/></svg>`}
function makePptx(title,slides){slides=Array.isArray(slides)&&slides.length?slides:[{title,body:''}];const entries=[];entries.push(['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>${slides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>`]);
entries.push(['_rels/.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>']);
entries.push(['ppt/presentation.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+2}"/>`).join('')}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/></p:presentation>`]);
entries.push(['ppt/_rels/presentation.xml.rels',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>${slides.map((_,i)=>`<Relationship Id="rId${i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join('')}</Relationships>`]);
entries.push(['ppt/slideMasters/slideMaster1.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles/></p:sldMaster>']);
entries.push(['ppt/slideMasters/_rels/slideMaster1.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>']);
entries.push(['ppt/slideLayouts/slideLayout1.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld></p:sldLayout>']);
entries.push(['ppt/slideLayouts/_rels/slideLayout1.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>']);
entries.push(['ppt/theme/theme1.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Super Maquina"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:srgbClr val="111827"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F2937"/></a:dk2><a:lt2><a:srgbClr val="F8FAFC"/></a:lt2><a:accent1><a:srgbClr val="B8911F"/></a:accent1><a:accent2><a:srgbClr val="334155"/></a:accent2><a:accent3><a:srgbClr val="64748B"/></a:accent3><a:accent4><a:srgbClr val="0F172A"/></a:accent4><a:accent5><a:srgbClr val="94A3B8"/></a:accent5><a:accent6><a:srgbClr val="CBD5E1"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="Office"><a:majorFont/><a:minorFont/></a:fontScheme><a:fmtScheme name="Office"><a:fillStyleLst/><a:lnStyleLst/><a:effectStyleLst/><a:bgFillStyleLst/></a:fmtScheme></a:themeElements></a:theme>']);
slides.forEach((s,i)=>{const body=String(s.body||'').split('\n').filter(Boolean).slice(0,10).map(x=>`<a:p><a:r><a:rPr lang="pt-BR" sz="1800"/><a:t>${xmlEsc(x)}</a:t></a:r></a:p>`).join('');const slide=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Título"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="700000" y="500000"/><a:ext cx="10800000" cy="1100000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="pt-BR" sz="3000" b="1"/><a:t>${xmlEsc(s.title||title)}</a:t></a:r></a:p></p:txBody></p:sp><p:sp><p:nvSpPr><p:cNvPr id="3" name="Conteúdo"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="900000" y="1800000"/><a:ext cx="10200000" cy="4200000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/>${body||'<a:p/>'}</p:txBody></p:sp></p:spTree></p:cSld></p:sld>`;entries.push([`ppt/slides/slide${i+1}.xml`,slide]);entries.push([`ppt/slides/_rels/slide${i+1}.xml.rels`,'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>']);});
return zipStore(entries)}
module.exports={makeDocx,makePdf,makePng,makeQrPng,makeQrSvg,makePptx};
