'use strict';
// Free-plan MCP OAuth. No paid REST API key and no inherited ChatGPT credentials.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
function createMetricool({data,port,enc,dec}){
 const pending=new Map(),file=path.join(data,'metricool-oauth.enc');
 let accounts={};if(fs.existsSync(file)){try{accounts=JSON.parse(dec(fs.readFileSync(file,'utf8')))}catch{}}
 const persist=()=>fs.writeFileSync(file,enc(JSON.stringify(accounts)),{mode:0o600});
 async function http(url,opts={}){const r=await fetch(url,{signal:AbortSignal.timeout(25000),...opts});const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error('Metricool respondeu em formato inesperado.')}if(!r.ok)throw new Error('Metricool: '+(d.error_description||d.error||r.status));return d}
 async function connect(cid){const redirect=`http://localhost:${port}/api/content-engine/metricool-callback`;const registration=await http('https://app.metricool.com/oauth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_name:'Super Máquina de Conteúdo local',redirect_uris:[redirect],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'})});if(!registration.client_id)throw new Error('Metricool não registrou a aplicação local.');const state=crypto.randomBytes(24).toString('base64url'),verifier=crypto.randomBytes(48).toString('base64url');pending.set(state,{cid,verifier,registration,redirect,expires:Date.now()+600000});const u=new URL('https://app.metricool.com/oauth/authorize');u.search=new URLSearchParams({response_type:'code',client_id:registration.client_id,redirect_uri:redirect,scope:'mcp:read mcp:write',state,code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',resource:'https://ai.metricool.com/mcp'}).toString();return{url:u.href,message:'Autorize sua conta Metricool. O plano gratuito será mantido.'}}
 async function callback(q){const p=pending.get(q.state);pending.delete(q.state);if(!p||p.expires<Date.now())throw new Error('Autorização expirada. Clique em conectar novamente.');if(q.error)throw new Error('Autorização não concluída: '+q.error);const tokens=await http('https://app.metricool.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code:q.code||'',client_id:p.registration.client_id,redirect_uri:p.redirect,code_verifier:p.verifier,resource:'https://ai.metricool.com/mcp'})});if(!tokens.access_token)throw new Error('Acesso não concedido.');accounts[p.cid]={clientId:p.registration.client_id,...tokens,expiresAt:Date.now()+Number(tokens.expires_in||3600)*1000};persist();return p.cid}
 async function token(cid){const a=accounts[cid];if(!a)throw new Error('Autorize o Metricool nesta aplicação.');if(Date.now()>a.expiresAt-60000&&a.refresh_token){const t=await http('https://app.metricool.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:a.refresh_token,client_id:a.clientId})});Object.assign(a,t,{expiresAt:Date.now()+Number(t.expires_in||3600)*1000});persist()}return a.access_token}
 async function rpc(cid,method,params,session){const headers={'Authorization':'Bearer '+await token(cid),'Content-Type':'application/json','Accept':'application/json, text/event-stream','MCP-Protocol-Version':'2025-03-26'};if(session)headers['Mcp-Session-Id']=session;const r=await fetch('https://ai.metricool.com/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(30000)});const text=await r.text();if(!r.ok)throw new Error('Metricool MCP retornou '+r.status+'. Reconecte se necessário.');let d;try{d=JSON.parse(text)}catch{for(const line of text.split('\n').filter(x=>x.startsWith('data:'))){try{const v=JSON.parse(line.slice(5));if(v.id===1)d=v}catch{}}}if(d?.error)throw new Error(d.error.message);if(!d)throw new Error('Sem confirmação válida do Metricool.');return{result:d.result,session:r.headers.get('mcp-session-id')||session}}
 async function read(cid,kind,args={}){const init=await rpc(cid,'initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'super-maquina',version:'0.4.0'}});await fetch('https://ai.metricool.com/mcp',{method:'POST',headers:{Authorization:'Bearer '+await token(cid),'Content-Type':'application/json',Accept:'application/json, text/event-stream',...(init.session?{'Mcp-Session-Id':init.session}:{})},body:JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'}),signal:AbortSignal.timeout(15000)});const list=await rpc(cid,'tools/list',{},init.session);if(kind==='tools')return list.result;const available=list.result?.tools||[];const normalized=n=>n.toLowerCase().replace(/[^a-z]/g,'');const allowed={brands:'getbrandsettings',scheduled:'getscheduledposts'};if(!allowed[kind])throw new Error('Leitura não reconhecida.');const tool=available.find(t=>normalized(t.name).endsWith(allowed[kind]));if(!tool)throw new Error('A conta não disponibilizou essa capacidade de leitura.');return(await rpc(cid,'tools/call',{name:tool.name,arguments:args},init.session)).result}
 return{connect,callback,read,configured:cid=>!!accounts[cid]};
}
module.exports={createMetricool};
